#!/bin/bash
# ==============================================================================
# Git Hooks 安装/更新脚本
#
# 使用方式:
#   curl -fsSL https://raw.githubusercontent.com/QuPlay/devops-java/main/scripts/install-hooks.sh | bash
# ==============================================================================

DEVOPS_REPO="https://github.com/QuPlay/devops-java.git"
HOOKS_DIR=".git/hooks"
LOCAL_VERSION_FILE="$HOOKS_DIR/.version"
TEMP_DIR="/tmp/devops-java-$$"
LAST_SYNC_FILE="$HOOKS_DIR/.last-sync"
GITHOOKS_DIR=".githooks"

# 只在项目根目录执行（.git 是目录而非文件）
if [ ! -d ".git" ]; then
    exit 0
fi

# 检测是否在 git hook 中执行
IN_GIT_HOOK=false
if [ -n "$GIT_DIR" ] || [ -n "$GIT_INDEX_FILE" ]; then
    IN_GIT_HOOK=true
fi

# 获取本地版本
LOCAL_VERSION=""
[ -f "$LOCAL_VERSION_FILE" ] && LOCAL_VERSION=$(cat "$LOCAL_VERSION_FILE" 2>/dev/null | tr -d '[:space:]')

# 远程版本权威判定 (curl 5 字节 .version, ~50ms; 加 timestamp 绕 CDN 缓存)
# 这是所有路径 (mvn / commit / 手动) 共享的判定依据, 不依赖本地 ../devops-java/ 是否最新
VERSION_URL="https://raw.githubusercontent.com/QuPlay/devops-java/main/quality/hooks/.version"
REMOTE_VERSION=$(curl -fsSL --max-time 5 "${VERSION_URL}?_=$(date +%s)" 2>/dev/null | tr -d '[:space:]')

# 判定是否必须更新:
#   - LOCAL 为空 (首次安装)
#   - DEVOPS_FORCE_UPDATE=1 (旁路调试用)
#   - LOCAL ≠ REMOTE (版本变化, 必须拉最新)
NEEDS_UPDATE=false
if [ -z "$LOCAL_VERSION" ]; then
    NEEDS_UPDATE=true
elif [ "$DEVOPS_FORCE_UPDATE" = "1" ]; then
    NEEDS_UPDATE=true
elif [ -n "$REMOTE_VERSION" ] && [ "$LOCAL_VERSION" != "$REMOTE_VERSION" ]; then
    NEEDS_UPDATE=true
fi

# 不需要更新时, 走 60s 节流和 IN_GIT_HOOK 短路 (减少不必要的工作)
# 反之版本不一致 / 首次安装会无视节流和 hook 短路, 保证最新版被拉到
if [ "$NEEDS_UPDATE" != true ]; then
    if [ -f "$LAST_SYNC_FILE" ]; then
        LAST_SYNC=$(cat "$LAST_SYNC_FILE" 2>/dev/null)
        NOW=$(date +%s)
        if [ -n "$LAST_SYNC" ] && [ $((NOW - LAST_SYNC)) -lt 60 ]; then
            exit 0
        fi
    fi
    if [ "$IN_GIT_HOOK" = true ]; then
        date +%s > "$LAST_SYNC_FILE" 2>/dev/null
        exit 0
    fi
fi

# NEEDS_UPDATE 时让下游 get_devops_path 强制 git clone (不读可能陈旧的 ../devops-java/)
if [ "$NEEDS_UPDATE" = true ]; then
    DEVOPS_FORCE_UPDATE=1
fi

# 获取 devops 仓库路径（优先本地，降级远程 clone）
# DEVOPS_FORCE_UPDATE=1 时强制走远程 clone, 跳过本地目录
# (本地目录可能陈旧未 git pull, bootstrap 检测到版本不一致时必须拿远程最新)
get_devops_path() {
    if [ "$DEVOPS_FORCE_UPDATE" != "1" ]; then
        for dir in "../goplay-devops" "../devops-java" "../DevOps-Java"; do
            if [ -d "$dir/quality" ]; then
                echo "$dir"
                return 0
            fi
        done
    fi
    rm -rf "$TEMP_DIR"
    git clone -q --depth 1 "$DEVOPS_REPO" "$TEMP_DIR" 2>/dev/null || return 1
    echo "$TEMP_DIR"
}

# 同步 CLAUDE.md 和审查规则
sync_assets() {
    local devops_path="$1"

    # 同步审查规则到 .git/rules/（供 pre-commit hook 拼装 review prompt）
    if [ -d "$devops_path/quality/rules" ]; then
        mkdir -p ".git/rules"
        cp "$devops_path/quality/rules/"*.md ".git/rules/" 2>/dev/null || true
    fi

    # 同步 CLAUDE.md
    local claude_src="$devops_path/quality/claude/CLAUDE.md"
    if [ -f "$claude_src" ]; then
        local header="<!-- AUTO-GENERATED by DevOps install-hooks.sh. Master: goplay-devops/quality/claude/CLAUDE.md -->"
        # 同步到项目根目录
        { echo "$header"; echo ""; cat "$claude_src"; } > "CLAUDE.md"
        # 确保 CLAUDE.md 在 .gitignore 中（自动生成文件不应提交）
        if [ -f ".gitignore" ] && ! grep -q "^CLAUDE\.md$" ".gitignore" 2>/dev/null; then
            printf '\n# Auto-generated by DevOps hooks\nCLAUDE.md\n' >> ".gitignore"
        fi
        # 若已被 git 跟踪，移除跟踪（保留磁盘文件）
        # 跳过 git hook 执行期间，避免修改 index 干扰正在进行的 commit
        if [ "$IN_GIT_HOOK" != true ] && git ls-files --error-unmatch CLAUDE.md >/dev/null 2>&1; then
            git rm --cached CLAUDE.md -q 2>/dev/null || true
        fi
        # 同步到工作区根目录（父目录，多仓库共享）
        if [ -d ".." ] && { [ ! -f "../.git/HEAD" ] || [ -d "../goplay-bom" ]; }; then
            { echo "$header"; echo ""; cat "$claude_src"; } > "../CLAUDE.md" 2>/dev/null || true
        fi
        echo "[DevOps] CLAUDE.md synced"
    fi
}

# 同步 bootstrap hooks 到 .githooks/（确保 core.hooksPath 指向的目录包含所有 bootstrap）
sync_bootstrap() {
    local devops_path="$1"
    local bootstrap_src="$devops_path/quality/bootstrap"
    if [ -d "$bootstrap_src" ]; then
        mkdir -p "$GITHOOKS_DIR"
        cp "$bootstrap_src/"* "$GITHOOKS_DIR/" 2>/dev/null || true
        chmod +x "$GITHOOKS_DIR"/* 2>/dev/null || true
        echo "[DevOps] Bootstrap hooks synced to $GITHOOKS_DIR/"
    fi
}

# 环境检测函数
check_environment() {
    echo "[DevOps] 检测开发环境..."
    local has_error=false

    # 检测 Python 3 (支持 python3 或 python 命令)
    local python_cmd=""
    local python_version=""
    if command -v python3 &> /dev/null; then
        python_cmd="python3"
        python_version=$(python3 --version 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
    elif command -v python &> /dev/null; then
        # 检查 python 是否为 Python 3
        python_version=$(python --version 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        if echo "$python_version" | grep -qE '^3\.'; then
            python_cmd="python"
        fi
    fi

    if [ -n "$python_cmd" ]; then
        echo "[DevOps]   ✓ Python ${python_version} (${python_cmd})"
    else
        echo "[DevOps]   ✗ Python 3 未安装 (必需)"
        has_error=true
    fi

    if command -v claude &> /dev/null; then
        echo "[DevOps]   ✓ claude CLI"
    else
        echo "[DevOps]   ✗ claude CLI 未安装"
        echo "[DevOps]     安装: npm install -g @anthropic-ai/claude-code"
        has_error=true
    fi

    local sonarlint_found=false
    [ -d ".idea/sonarlint" ] || [ -f ".idea/sonarlint.xml" ] && sonarlint_found=true
    [ -d "$HOME/Library/Application Support/JetBrains" ] && ls "$HOME/Library/Application Support/JetBrains"/*/plugins/sonarlint* >/dev/null 2>&1 && sonarlint_found=true
    [ -d "$HOME/.local/share/JetBrains" ] && ls "$HOME/.local/share/JetBrains"/*/plugins/sonarlint* >/dev/null 2>&1 && sonarlint_found=true
    [ -d "$APPDATA/JetBrains" ] && ls "$APPDATA/JetBrains"/*/plugins/sonarlint* >/dev/null 2>&1 && sonarlint_found=true

    if [ "$sonarlint_found" = true ]; then
        echo "[DevOps]   ✓ SonarQube for IDE"
    else
        echo "[DevOps]   ✗ SonarQube for IDE 未安装"
        echo "[DevOps]     安装: IDEA → Settings → Plugins → 搜索 'SonarQube for IDE'"
    fi

    if [ "$has_error" = true ]; then
        echo "[DevOps] ⚠ 请安装缺失的工具以启用完整功能"
    fi
}

# 如果本地没有 hooks，直接安装
if [ -z "$LOCAL_VERSION" ]; then
    echo "[DevOps] Git Hooks 未安装，正在安装..."
    DEVOPS_PATH=$(get_devops_path) || { echo "[DevOps] 警告: 无法获取 devops-java"; exit 0; }

    mkdir -p "$HOOKS_DIR"
    cp "$DEVOPS_PATH/quality/hooks/"* "$HOOKS_DIR/" 2>/dev/null || true
    cp "$DEVOPS_PATH/quality/hooks/".* "$HOOKS_DIR/" 2>/dev/null || true
    chmod +x "$HOOKS_DIR"/* 2>/dev/null || true
    sync_assets "$DEVOPS_PATH"
    sync_bootstrap "$DEVOPS_PATH"

    # 设置 core.hooksPath 确保 .githooks bootstrap 能被 git 触发
    if [ -d "$GITHOOKS_DIR" ]; then
        CURRENT_HOOKS_PATH=$(git config core.hooksPath 2>/dev/null || echo "")
        if [ "$CURRENT_HOOKS_PATH" != "$GITHOOKS_DIR" ]; then
            git config core.hooksPath "$GITHOOKS_DIR"
            echo "[DevOps] core.hooksPath set to $GITHOOKS_DIR"
        fi
    fi

    [ -d "$TEMP_DIR" ] && rm -rf "$TEMP_DIR"
    NEW_VERSION=$(cat "$HOOKS_DIR/.version" 2>/dev/null | tr -d '[:space:]')
    echo "[DevOps] Git Hooks 安装完成 (v${NEW_VERSION})"
    date +%s > "$LAST_SYNC_FILE"
    check_environment

    # 如果从 git hook 中安装，返回特殊退出码 100，通知 bootstrap 重新执行
    if [ "$IN_GIT_HOOK" = true ]; then
        exit 100
    fi
    exit 0
fi

# 如果在 git hook 中执行且版本一致 (NEEDS_UPDATE=false 已在前面 exit 0),
# 走到这里意味着本地版本陈旧或 FORCE 模式, 应该执行更新。
# 旧版的 IN_GIT_HOOK 无条件 exit 0 已被前置版本检查替代。

# 检查是否需要更新（比较版本）
DEVOPS_PATH=$(get_devops_path) || { date +%s > "$LAST_SYNC_FILE"; exit 0; }
REMOTE_VERSION=$(cat "$DEVOPS_PATH/quality/hooks/.version" 2>/dev/null | tr -d '[:space:]')

if [ "$LOCAL_VERSION" != "$REMOTE_VERSION" ]; then
    echo "[DevOps] Git Hooks 更新: v${LOCAL_VERSION} -> v${REMOTE_VERSION}"
    cp "$DEVOPS_PATH/quality/hooks/"* "$HOOKS_DIR/" 2>/dev/null || true
    cp "$DEVOPS_PATH/quality/hooks/".* "$HOOKS_DIR/" 2>/dev/null || true
    chmod +x "$HOOKS_DIR"/* 2>/dev/null || true
    sync_assets "$DEVOPS_PATH"
    sync_bootstrap "$DEVOPS_PATH"
    echo "[DevOps] Git Hooks 更新完成"
fi

# 确保 core.hooksPath 始终正确（修复旧版本安装遗留）
if [ -d "$GITHOOKS_DIR" ]; then
    CURRENT_HOOKS_PATH=$(git config core.hooksPath 2>/dev/null || echo "")
    if [ "$CURRENT_HOOKS_PATH" != "$GITHOOKS_DIR" ]; then
        git config core.hooksPath "$GITHOOKS_DIR"
        echo "[DevOps] core.hooksPath set to $GITHOOKS_DIR"
    fi
fi

[ -d "$TEMP_DIR" ] && rm -rf "$TEMP_DIR"
date +%s > "$LAST_SYNC_FILE"
exit 0
