#!/usr/bin/env bash
#
# sync-claude-md.sh — Sync master CLAUDE.md to current project.
#
# Usage (from any service repo root):
#   /path/to/goplay-devops/scripts/sync-claude-md.sh
#
# Or from goplay-devops itself:
#   ./scripts/sync-claude-md.sh
#
# Normally you don't need this — install-hooks.sh handles it automatically
# on hook install/update. This script is for manual one-off sync.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEVOPS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MASTER="${DEVOPS_ROOT}/quality/claude/CLAUDE.md"

if [[ ! -f "$MASTER" ]]; then
    echo "ERROR: Master CLAUDE.md not found at $MASTER" >&2
    exit 1
fi

HEADER="<!-- AUTO-GENERATED by DevOps sync-claude-md.sh. Master: goplay-devops/quality/claude/CLAUDE.md -->"

sync_to() {
    local target="$1"
    { echo "$HEADER"; echo ""; cat "$MASTER"; } > "$target"
    echo "  OK   $target"
}

# Detect project root (look for .git directory)
PROJECT_ROOT=""
if [ -d ".git" ]; then
    PROJECT_ROOT="$(pwd)"
fi

echo "Syncing CLAUDE.md from: $MASTER"
echo ""

if [ -n "$PROJECT_ROOT" ]; then
    # Running from a service repo — sync to project root
    sync_to "${PROJECT_ROOT}/CLAUDE.md"

    # Also sync to workspace root (parent) if it's not a git repo
    PARENT="$(cd .. && pwd)"
    if [ ! -d "$PARENT/.git" ]; then
        sync_to "${PARENT}/CLAUDE.md"
    fi
else
    # Running from non-git directory (e.g., workspace root) — sync here
    sync_to "$(pwd)/CLAUDE.md"
fi

echo ""
echo "Done."
